//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.Shared.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category does not exist.
        /// </summary>
        public static string CategoryDoesNotExist {
            get {
                return ResourceManager.GetString("CategoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category id cannot be empty.
        /// </summary>
        public static string CategoryIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("CategoryIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name cannot be empty.
        /// </summary>
        public static string CategoryNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("CategoryNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is not unique.
        /// </summary>
        public static string CategoryNameIsNotUnique {
            get {
                return ResourceManager.GetString("CategoryNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must have appropriate format: png, jpg, svg.
        /// </summary>
        public static string FileMustHaveAppropriateFormat {
            get {
                return ResourceManager.GetString("FileMustHaveAppropriateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory does not exist.
        /// </summary>
        public static string FileMustHaveAppropriateFormat {
            get {
                return ResourceManager.GetString("FileMustHaveAppropriateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subcategory does not exist.
        /// </summary>
        public static string SubcategoryDoesNotExist {
            get {
                return ResourceManager.GetString("SubcategoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory id cannot be empty.
        /// </summary>
        public static string SubcategoryIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("SubcategoryIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory name cannot be empty.
        /// </summary>
        public static string SubcategoryNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("SubcategoryNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory name is not unique.
        /// </summary>
        public static string SubcategoryNameIsNotUnique {
            get {
                return ResourceManager.GetString("SubcategoryNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team id can not be empty.
        /// </summary>
        public static string TeamIdCanNotBeEmpty {
            get {
                return ResourceManager.GetString("TeamIdCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with that id does not exist.
        /// </summary>
        public static string TeamIdDoesNotExist {
            get {
                return ResourceManager.GetString("TeamIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team logo cannot be empty.
        /// </summary>
        public static string TeamLogoCannotBeEmpty {
            get {
                return ResourceManager.GetString("TeamLogoCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name cannot be empty.
        /// </summary>
        public static string TeamNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("TeamNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name is not unique.
        /// </summary>
        public static string TeamNameIsNotUnique {
            get {
                return ResourceManager.GetString("TeamNameIsNotUnique", resourceCulture);
            }
        }
    }
}
