//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsHub.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsHub.Shared.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category does not exist.
        /// </summary>
        public static string CategoryDoesNotExist {
            get {
                return ResourceManager.GetString("CategoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category id cannot be empty.
        /// </summary>
        public static string CategoryIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("CategoryIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category name cannot be empty.
        /// </summary>
        public static string CategoryNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("CategoryNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category name is not unique.
        /// </summary>
        public static string CategoryNameIsNotUnique {
            get {
                return ResourceManager.GetString("CategoryNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File must have appropriate format: png, jpg, svg.
        /// </summary>
        public static string FileMustHaveAppropriateFormat {
            get {
                return ResourceManager.GetString("FileMustHaveAppropriateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subcategory does not exist.
        /// </summary>
        public static string SubcategoryDoesNotExist {
            get {
                return ResourceManager.GetString("SubcategoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subcategory id cannot be empty.
        /// </summary>
        public static string SubcategoryIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("SubcategoryIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subcategory name cannot be empty.
        /// </summary>
        public static string SubcategoryNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("SubcategoryNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subcategory name is not unique.
        /// </summary>
        public static string SubcategoryNameIsNotUnique {
            get {
                return ResourceManager.GetString("SubcategoryNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Team name cannot be empty.
        /// </summary>
        public static string TeamNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("TeamNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Team name is not unique.
        /// </summary>
        public static string TeamNameIsNotUnique {
            get {
                return ResourceManager.GetString("TeamNameIsNotUnique", resourceCulture);
            }
        }
    }
}
