name: Health Check for SportsHub API

on:
  pull_request:
    branches:
      - dev
      - topic/*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build --configuration Release ./src

      - name: Test
        run: dotnet test --configuration Release ./src 
